### ISSUE TITLE
Suggestion: Use GitHub releases?

### ISSUE THREAD

**Issue by Raymonf** [syntax-dev-br/GCNet#2]
Why not just use [GitHub's releases](https://github.com/SyntaxGC/GCNet/releases) function?

I get that it might be a little less convenient than Dropbox, but it gets tied into GitHub better.

**Comment by syntax-dev-br** [comment]
Sorry, I'm new to GitHub and didn't know about this feature. It's surely better than using Dropbox. I'm actually using it right now, thanks for the tip: [https://github.com/syntax-dev-br/GCNet/releases](url).
