### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by rocverde** [syntax-dev-br/GCNet#6]
Hi there!
Is there any email address or other way that I could use to contact you? I would like to talk about your library and the development of other grand chase seasons.
---
Ola!
Existe algum email ou algum outro metodo que eu possa usar para falar com voce? Queria conversar sobre sua library, e sobre o desenvolvemento de outras seasons de grand chase.
Fico no aguardo!
Roverde

**Comment by syntax-dev-br** [comment]
Olá, @rocverde .

Peço mil desculpas por esse tremendo atraso na resposta, estive ausente na minha conta do GitHub durante meses e só tive a oportunidade de ler sua issue agora. Caso ainda tenha interesse em entrar em contato comigo, fique à vontade para mandar um e-mail para syntaxdevbr@gmail.com. 
Atenciosamente, SyntaxDev.
